name: linter-check
on: pull_request

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: |
          npm run prettier:fix
          npm run lint:fix

      - name: Check for changes
        id: git_diff
        run: |
          git diff --exit-code || echo "changed=1" >> $GITHUB_OUTPUT

      - name: Commit if code changed by linter
        if: ${{ steps.git_diff.outputs.changed == 1 }}
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: fix code style issues with linters'
          git push
